list=[1,2,3]
more=[11,12,13]
list.append(4)
print(list)
list.append(( '5a', '5b' ))
print(list)
list.extend(more)
print(list)
list.index(11)
print(list)
list.insert( 6,'Six' )
print(list)
list.pop()
print(list)
list.pop(4)
print(list)
list.remove('Six')
print(list)
list.remove(4)
print(list)
list.reverse()
print(list)
list.sort()
print(list)
x=[2,1,4,6,9]
x.sort()
print(x)